### ISSUE TITLE
typography.js

### ISSUE THREAD

**Issue by ghost** [h0tc0d3/postcss-hamster#1]
А чем не угодил [typography](https://github.com/KyleAMathews/typography.js) 

[Demo](http://kyleamathews.github.io/typography.js/)

```javascript
import Typography from 'typography'
import funstonTheme from 'typography-theme-funston'
funston.overrideThemeStyles = ({ rhythm }, options) => ({
  'h2,h3': {
    marginBottom: rhythm(1/2),
    marginTop: rhythm(2),
  }
})
```
там еще бонусом множество уже готовых стилей типографики

**Comment by h0tc0d3** [comment]
Тем, что надо писать CSS, а не JS код, ближе к верстальщикам итд. Плюс синтаксис 'typography' не дружелюбный. У меня все просто и разберется даже новичек. Плюс в следующей версии еще будут киллер фичи. Во вторых это не просто типографика, а полноценный фреймворк, функции которого будут расширяться. Вроде как у меня единственного генерится PNG сетка для отладки ритма в старых браузерах. У всех используется linear-gradient. Вот средний результат бенчмарка при 110 запусках на большом css файле, мой инструмент еще и самый быстрый. Если отнять 25мс, что забирает postcss, то мой плагин делает работу за 12-17мс.
```
devHamster                Time: 37.91818181818182ms.
devHamster                Time: 42.78181818181818ms
```
