### ISSUE TITLE
Domain hamster.im doesn't seem to be working?

### ISSUE THREAD

**Issue by Cobertos** [h0tc0d3/postcss-hamster#2]
See attached image...
![image](https://user-images.githubusercontent.com/6759176/75075966-01982b00-54cd-11ea-84ed-f603fa8a0faf.png)

nic.im does seem to be working for me though so I don't believe this is a ccTLD problem

**Comment by h0tc0d3** [comment]
Sorry. The project did not receive proper support and was closed. Plus, I ran into backward compatibility issues with other postcss modules.  Dumb developers scored on web standards compatibility and lazily correct errors. I had more developments for new version, but unfortunately did not upload them You can see hamster demo and mirror of website here 

https://h0tc0d3.github.io/hamster/

Thank you! Good luck!
